### ISSUE TITLE
unable to pass splash color as a parameter of the `RiveAnimatedIcon`

### ISSUE THREAD

**Issue by JordyHers** [nikkieke/rive_animated_icons#1]
## Description:

Currently when using the **RiveAnimatedIcon** the user can smoothly interact with the animation and stop it (if loop is true). However he is not able to pass a custom splash color property to the **RiveAnimatedIcon.** This results in a bit unpleasing UI/UX for dark background apps.

**Comment by nikkieke** [comment]
Hi Jordy, you can check out v1.1.2  for this update.
Thanks!
