### ISSUE TITLE
Is there a way to see the entire list of available icons?

### ISSUE THREAD

**Issue by mark8044** [nikkieke/rive_animated_icons#3]
Is there a way to see the entire list of available icons?

**Comment by nikkieke** [comment]
Hi,
Yeah, the README file showcases all the available icons in the icons sample section, alternatively you can check the [config file ](https://github.com/nikkieke/rive_animated_icons/blob/main/lib/src/config.dart)in the project to see all available icons.

**Comment by mark8044** [comment]
I see thank you
